name: Node.js CI

on:
  push:
    branches:
      - main
      - beta
  pull_request:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      id: nvm
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
    - run: yarn install
    - run: yarn ci

